version: '3.8'

services:
  tarantool:
    image: tarantool/tarantool:2.10
    container_name: tarantool
    ports:
      - "3301:3301"
    environment:
      TARANTOOL_MEMORY: 512M
    command: tarantool /opt/tarantool/config.lua
    volumes:
      - ./tarantool/config.lua:/opt/tarantool/config.lua:ro

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poll-bot
    ports:
      - "8000:8000"
    depends_on:
      - tarantool
    environment:
      TARANTOOL_HOST: tarantool
      TARANTOOL_PORT: 3301